services:
  - type: web
    name: mern-portfolio
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000